#!/bin/bash
unicycler -1 prinseq_output/polished_cutadapt/polished/S_32_S18_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_32_S18_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_32_S18
unicycler -1 prinseq_output/polished_cutadapt/polished/S_FM_ATCC_S22_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_FM_ATCC_S22_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_FM_ATCC_S22
unicycler -1 prinseq_output/polished_cutadapt/polished/S_FM_DSM_S23_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_FM_DSM_S23_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_FM_DSM_S23
unicycler -1 prinseq_output/polished_cutadapt/polished/S_IMP_BC_01_S43_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_IMP_BC_01_S43_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_IMP_BC_01_S43
unicycler -1 prinseq_output/polished_cutadapt/polished/S_IMP_BC_02_S44_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_IMP_BC_02_S44_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_IMP_BC_02_S44
unicycler -1 prinseq_output/polished_cutadapt/polished/S_IMP_BC_04_S45_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_IMP_BC_04_S45_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_IMP_BC_04_S45
unicycler -1 prinseq_output/polished_cutadapt/polished/S_IMP_PBS-GLY_S42_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_IMP_PBS-GLY_S42_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_IMP_PBS-GLY_S42
unicycler -1 prinseq_output/polished_cutadapt/polished/S_Josh_DNF00844_S49_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_Josh_DNF00844_S49_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_Josh_DNF00844_S49
unicycler -1 prinseq_output/polished_cutadapt/polished/S_Josh_KA00225_S25_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_Josh_KA00225_S25_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_Josh_KA00225_S25
unicycler -1 prinseq_output/polished_cutadapt/polished/S_Josh_KA00625_S24_polished_1.fastq -2 prinseq_output/polished_cutadapt/polished/S_Josh_KA00625_S24_polished_2.fastq --mode normal --threads 40 --keep 2 --depth_filter 0.2 --min_fasta_length 1000 --out unicycler_output_S_Josh_KA00625_S24
